// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Music_Organizer.Data;

#nullable disable

namespace Music_Organizer.Migrations
{
    [DbContext(typeof(MusicOrganizerDbContext))]
    [Migration("20260106033719_AddInterludeFlag")]
    partial class AddInterludeFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Music_Organizer.Data.AlbumConclusionEntity", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Score")
                        .HasColumnType("REAL");

                    b.HasKey("AlbumId");

                    b.ToTable("AlbumConclusions");
                });

            modelBuilder.Entity("Music_Organizer.Data.AlbumEntity", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlbumId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Music_Organizer.Data.TrackEntity", b =>
                {
                    b.Property<Guid>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackId");

                    b.HasIndex("AlbumId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Music_Organizer.Data.TrackReviewEntity", b =>
                {
                    b.Property<Guid>("TrackReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInterlude")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Score")
                        .HasColumnType("REAL");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.HasKey("TrackReviewId");

                    b.HasIndex("TrackId")
                        .IsUnique();

                    b.HasIndex("AlbumId", "TrackId")
                        .IsUnique();

                    b.ToTable("TrackReviews");
                });

            modelBuilder.Entity("Music_Organizer.Data.AlbumConclusionEntity", b =>
                {
                    b.HasOne("Music_Organizer.Data.AlbumEntity", "Album")
                        .WithOne("Conclusion")
                        .HasForeignKey("Music_Organizer.Data.AlbumConclusionEntity", "AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Music_Organizer.Data.TrackEntity", b =>
                {
                    b.HasOne("Music_Organizer.Data.AlbumEntity", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Music_Organizer.Data.TrackReviewEntity", b =>
                {
                    b.HasOne("Music_Organizer.Data.AlbumEntity", "Album")
                        .WithMany("TrackReviews")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Music_Organizer.Data.TrackEntity", "Track")
                        .WithOne("Review")
                        .HasForeignKey("Music_Organizer.Data.TrackReviewEntity", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Music_Organizer.Data.AlbumEntity", b =>
                {
                    b.Navigation("Conclusion")
                        .IsRequired();

                    b.Navigation("TrackReviews");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Music_Organizer.Data.TrackEntity", b =>
                {
                    b.Navigation("Review")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
